version: "3.9"

services:
  ### Pre-load models into the cache
  # docling-model-cache-load:
  #   image: ghcr.io/docling-project/docling-serve-cpu:v1.9.0
  #   command:
  #     - docling-tools
  #     - models
  #     - download
  #     - '--output-dir=/models'
  #     - 'layout'
  #     - 'tableformer'
  #     - 'code_formula'
  #     - 'picture_classifier'
  #     - 'granitedocling'
  #     - 'granite_vision'
  #     - 'easyocr'
  #     - 'rapidocr'
  #   volumes:
  #     - ./models:/models
  #   restart: "no"
  docling-serve:
    image: ghcr.io/docling-project/docling-serve-cu128:v1.9.0
    container_name: docling-serve
    ports:
      - "5001:5001"
    environment:
      DOCLING_SERVE_ENABLE_UI: "true"
      DOCLING_SERVE_ARTIFACTS_PATH: "/opt/app-root/src/models"
      NVIDIA_VISIBLE_DEVICES: "all"
      ### Extra settings
      # Enable remote services for API-based VLM models (GPT-4, etc.)
      DOCLING_SERVE_ENABLE_REMOTE_SERVICES: "true"
    devices:
      - "nvidia.com/gpu=all"
    restart: always
    volumes:
      - ./models:/opt/app-root/src/models
