"""Baseline schema for conversion service.

Revision ID: 57317cf19d3b
Revises:
Create Date: 2026-03-28 13:29:04.291883
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "57317cf19d3b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("karakeep_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("normalized_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_aizk_uuid"), ["aizk_uuid"], unique=True)
        batch_op.create_index(batch_op.f("ix_bookmarks_karakeep_id"), ["karakeep_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_bookmarks_normalized_url"), ["normalized_url"], unique=False)

    op.create_table(
        "conversion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("payload_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "QUEUED",
                "RUNNING",
                "UPLOAD_PENDING",
                "SUCCEEDED",
                "FAILED_RETRYABLE",
                "FAILED_PERM",
                "CANCELLED",
                name="conversionjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("earliest_next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aizk_uuid"],
            ["bookmarks.aizk_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversion_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversion_jobs_aizk_uuid"), ["aizk_uuid"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversion_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversion_jobs_earliest_next_attempt_at"), ["earliest_next_attempt_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_conversion_jobs_idempotency_key"), ["idempotency_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_conversion_jobs_status"), ["status"], unique=False)

    op.create_table(
        "conversion_outputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("payload_version", sa.Integer(), nullable=False),
        sa.Column("s3_prefix", sa.Text(), nullable=False),
        sa.Column("markdown_key", sa.Text(), nullable=False),
        sa.Column("manifest_key", sa.Text(), nullable=False),
        sa.Column("markdown_hash_xx64", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("figure_count", sa.Integer(), nullable=False),
        sa.Column("docling_version", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("pipeline_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aizk_uuid"],
            ["bookmarks.aizk_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["conversion_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversion_outputs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversion_outputs_aizk_uuid"), ["aizk_uuid"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversion_outputs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversion_outputs_job_id"), ["job_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_conversion_outputs_markdown_hash_xx64"), ["markdown_hash_xx64"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversion_outputs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversion_outputs_markdown_hash_xx64"))
        batch_op.drop_index(batch_op.f("ix_conversion_outputs_job_id"))
        batch_op.drop_index(batch_op.f("ix_conversion_outputs_created_at"))
        batch_op.drop_index(batch_op.f("ix_conversion_outputs_aizk_uuid"))

    op.drop_table("conversion_outputs")
    with op.batch_alter_table("conversion_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversion_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_conversion_jobs_idempotency_key"))
        batch_op.drop_index(batch_op.f("ix_conversion_jobs_earliest_next_attempt_at"))
        batch_op.drop_index(batch_op.f("ix_conversion_jobs_created_at"))
        batch_op.drop_index(batch_op.f("ix_conversion_jobs_aizk_uuid"))

    op.drop_table("conversion_jobs")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_normalized_url"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_karakeep_id"))
        batch_op.drop_index(batch_op.f("ix_bookmarks_aizk_uuid"))

    op.drop_table("bookmarks")
    # ### end Alembic commands ###
