"""Add the graph contextualization work-unit table.

Revision ID: a9c0d1e2f3b4
Revises: f8b9c0d1e2a3
Create Date: 2026-06-01 12:00:00.000000

Creates ``graph_contextualization_jobs`` — the graph stage's claimable work-unit
table, mirroring ``conversion_jobs``: one row per converted document to
chunk-persist and contextualize, scoped to the durable source identity
``aizk_uuid``. ``conversion_output_id`` and ``aizk_uuid`` are stored as plain
(logical) references — no cross-stage foreign keys — matching the graph stage's
run-reference convention and keeping the work-unit table self-contained. The
``status`` column mirrors the runtime's ``WorkUnitStatus`` (plain text, no named
enum), and the ``*_at`` columns carry retry/lease scheduling.

Lives in the conversion Alembic tree, which owns all tables for the single SQLite
database (ADR-003).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "a9c0d1e2f3b4"
down_revision: str | None = "f8b9c0d1e2a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the graph contextualization work-unit table and its indexes."""
    op.create_table(
        "graph_contextualization_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("conversion_output_id", sa.Integer(), nullable=False),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("earliest_next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_graph_contextualization_jobs_idempotency_key"),
    )
    op.create_index(
        "ix_graph_contextualization_jobs_claim",
        "graph_contextualization_jobs",
        ["status", "earliest_next_attempt_at", "queued_at"],
        unique=False,
    )
    op.create_index(
        "ix_graph_contextualization_jobs_aizk_uuid",
        "graph_contextualization_jobs",
        ["aizk_uuid"],
        unique=False,
    )
    op.create_index(
        "ix_graph_contextualization_jobs_conversion_output_id",
        "graph_contextualization_jobs",
        ["conversion_output_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the graph contextualization work-unit table and its indexes."""
    op.drop_index("ix_graph_contextualization_jobs_conversion_output_id", table_name="graph_contextualization_jobs")
    op.drop_index("ix_graph_contextualization_jobs_aizk_uuid", table_name="graph_contextualization_jobs")
    op.drop_index("ix_graph_contextualization_jobs_claim", table_name="graph_contextualization_jobs")
    op.drop_table("graph_contextualization_jobs")
