"""Add the contextualization output memo table.

Revision ID: c2d3e4f5a6b7
Revises: b0d1e2f3a4c5
Create Date: 2026-06-06 12:00:00.000000

Creates ``graph_contextualization_output_memo``, the internal scratch table that
caches validated contextualization model outputs (the document summary and each
per-chunk revision) keyed by ``(kind, scope_key, derivation_key)`` so a retry of a
partially-completed contextualization attempt re-invokes the model only for
outputs not already retained.

The memo is never a product projection — operator and explorer surfaces read the
``graph_document_summaries`` / ``graph_contextualized_chunks`` projections, never
this table. ``output_text`` allows ``''`` (a present-empty entry meaning the model
judged a chunk already self-contained, distinct from an absent entry). The unique
constraint on ``(kind, scope_key, derivation_key)`` makes the autonomous
insert-or-ignore upsert idempotent under the single serialized writer; the
matching index serves the exact-key lookups.

This lives in the conversion Alembic tree, which owns all tables for the single
SQLite database (ADR-003).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "c2d3e4f5a6b7"
down_revision: str | None = "b0d1e2f3a4c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the contextualization output memo table, its unique constraint, and index."""
    op.create_table(
        "graph_contextualization_output_memo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("scope_key", sa.String(), nullable=False),
        sa.Column("derivation_key", sa.Text(), nullable=False),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.CheckConstraint(
            "kind IN ('summary', 'revision')",
            name="ck_graph_contextualization_output_memo_kind",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "kind",
            "scope_key",
            "derivation_key",
            name="uq_graph_contextualization_output_memo_key",
        ),
    )
    op.create_index(
        "ix_graph_contextualization_output_memo_key",
        "graph_contextualization_output_memo",
        ["kind", "scope_key", "derivation_key"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the contextualization output memo table and its index."""
    op.drop_index(
        "ix_graph_contextualization_output_memo_key",
        table_name="graph_contextualization_output_memo",
    )
    op.drop_table("graph_contextualization_output_memo")
