"""Rename bookmarks -> sources, add source_ref columns, make karakeep_id nullable.

Revision ID: c3d4e5f6a7b8
Revises: b7f8e9a0c1d2
Create Date: 2026-04-15 00:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence
import hashlib
import json

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "c3d4e5f6a7b8"
down_revision: str | None = "b7f8e9a0c1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _karakeep_source_ref_json(karakeep_id: str) -> str:
    """Build the canonical source_ref JSON payload for a KaraKeep bookmark id."""
    return json.dumps(
        {"kind": "karakeep_bookmark", "bookmark_id": karakeep_id},
        separators=(",", ":"),
    )


def _karakeep_source_ref_hash(karakeep_id: str) -> str:
    """Compute source_ref_hash for a KaraKeep bookmark id.

    Matches the runtime formula: SHA-256 over ``json.dumps(to_dedup_payload(),
    sort_keys=True, separators=(",", ":"))``.
    """
    payload = {"kind": "karakeep_bookmark", "bookmark_id": karakeep_id}
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode()).hexdigest()


def upgrade() -> None:
    """Apply schema changes.

    1. Rename table bookmarks -> sources (SQLite >= 3.26 auto-updates FK references
       in conversion_jobs and conversion_outputs).
    2. Add source_ref (JSON) and source_ref_hash (unique text) columns to sources.
    3. Make karakeep_id nullable on sources.
    4. Backfill source_ref and source_ref_hash from karakeep_id for every existing row.
    5. Add source_ref (JSON) to conversion_jobs, backfilled from the owning source row.
    """
    op.rename_table("bookmarks", "sources")

    # Add new columns (source_ref_hash initially nullable so we can backfill, then tightened).
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_ref", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("source_ref_hash", sa.String(length=64), nullable=True))

    # Backfill existing rows.
    connection = op.get_bind()
    rows = connection.execute(sa.text("SELECT id, karakeep_id FROM sources")).fetchall()
    for row in rows:
        source_ref_json = _karakeep_source_ref_json(row.karakeep_id)
        source_ref_hash = _karakeep_source_ref_hash(row.karakeep_id)
        connection.execute(
            sa.text(
                "UPDATE sources SET source_ref = :ref, source_ref_hash = :hash WHERE id = :id"
            ),
            {"ref": source_ref_json, "hash": source_ref_hash, "id": row.id},
        )

    # Tighten nullability, make karakeep_id nullable, add unique index on the hash.
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.alter_column("source_ref", nullable=False)
        batch_op.alter_column("source_ref_hash", nullable=False)
        batch_op.alter_column("karakeep_id", nullable=True)
        batch_op.create_index(
            batch_op.f("ix_sources_source_ref_hash"),
            ["source_ref_hash"],
            unique=True,
        )

    # Add source_ref (JSON) to conversion_jobs, backfilled from the owning source row.
    with op.batch_alter_table("conversion_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_ref", sa.JSON(), nullable=True))

    connection.execute(
        sa.text(
            "UPDATE conversion_jobs SET source_ref = ("
            "SELECT source_ref FROM sources WHERE sources.aizk_uuid = conversion_jobs.aizk_uuid"
            ")"
        )
    )

    with op.batch_alter_table("conversion_jobs", schema=None) as batch_op:
        batch_op.alter_column("source_ref", nullable=False)


def downgrade() -> None:
    """Revert schema changes."""
    with op.batch_alter_table("conversion_jobs", schema=None) as batch_op:
        batch_op.drop_column("source_ref")

    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_source_ref_hash"))
        batch_op.alter_column("karakeep_id", nullable=False)
        batch_op.drop_column("source_ref_hash")
        batch_op.drop_column("source_ref")

    op.rename_table("sources", "bookmarks")
