"""Add pipeline_runs and pipeline_events tables for the shared stage runtime.

Revision ID: d0e1f2a3b4c5
Revises: a8c9d0e1f2b3
Create Date: 2026-05-23 12:00:00.000000

Creates the two additive primitives tables owned by ``aizk.pipeline``:

- ``pipeline_runs`` — the stage-run / dataset-version record keyed by
  ``(stage, scope_key)``, with a partial unique index enforcing at most one
  active run per scope.
- ``pipeline_events`` — the shared append-only transition-event log for all
  stages, keyed by the denormalized ``aizk_uuid`` source identity so a source's
  progress is resolvable across stages. ``work_unit_ref`` and ``run_id`` are
  logical references (no database foreign keys) so the table stays decoupled
  from any single stage's schema.

This migration lives in the conversion Alembic tree, which owns all tables for
the single SQLite database (ADR-003); ``aizk.pipeline`` stays import-independent
of ``aizk.conversion``.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "d0e1f2a3b4c5"
down_revision: str | None = "a8c9d0e1f2b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create pipeline_runs and pipeline_events with their indexes."""
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("scope_key", sa.String(), nullable=False),
        # status mirrors RunStatus (active|superseded); plain text, no named enum.
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("input_fingerprint", sa.Text(), nullable=False),
        sa.Column("version_stamps_json", sa.Text(), nullable=False),
        sa.Column("supersedes_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_runs_stage_scope_key",
        "pipeline_runs",
        ["stage", "scope_key"],
        unique=False,
    )
    # Partial unique index: at most one active run per (stage, scope_key).
    op.create_index(
        "uq_pipeline_runs_active_scope",
        "pipeline_runs",
        ["stage", "scope_key"],
        unique=True,
        sqlite_where=sa.text("status = 'active'"),
        postgresql_where=sa.text("status = 'active'"),
    )

    op.create_table(
        "pipeline_events",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("work_unit_ref", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_pipeline_events_aizk_uuid_occurred_at",
        "pipeline_events",
        ["aizk_uuid", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_events_stage_work_unit_ref_occurred_at",
        "pipeline_events",
        ["stage", "work_unit_ref", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_events_kind_occurred_at",
        "pipeline_events",
        ["kind", "occurred_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop pipeline_events and pipeline_runs and their indexes."""
    op.drop_index("ix_pipeline_events_kind_occurred_at", table_name="pipeline_events")
    op.drop_index("ix_pipeline_events_stage_work_unit_ref_occurred_at", table_name="pipeline_events")
    op.drop_index("ix_pipeline_events_aizk_uuid_occurred_at", table_name="pipeline_events")
    op.drop_table("pipeline_events")

    op.drop_index("uq_pipeline_runs_active_scope", table_name="pipeline_runs")
    op.drop_index("ix_pipeline_runs_stage_scope_key", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
