"""Relocate conversion_job_events into the shared pipeline_events table.

Revision ID: e1f2a3b4c5d6
Revises: d0e1f2a3b4c5
Create Date: 2026-05-28 12:00:00.000000

Structural relocation of conversion's transition-event log onto the shared
``pipeline_events`` primitive (design.md § ``PipelineEventsGenericSchema``).
Content-preserving: every ``conversion_job_events`` row is copied into
``pipeline_events`` with the same ``kind``, ``from_status`` / ``to_status``,
``payload_json``, ``aizk_uuid``, ``attempt``, and ``occurred_at`` — only the
column shape is genericized:

- ``stage`` is set to the constant ``'conversion'``.
- the integer ``job_id`` (FK, ``ON DELETE SET NULL``) becomes the text
  ``work_unit_ref`` (``CAST(job_id AS TEXT)``); rows whose job was deleted (NULL
  ``job_id``) get the literal ``'None'``, mirroring the runtime helper's
  ``str(None)`` and preserving the post-deletion audit via the already-populated
  ``aizk_uuid``.
- ``run_id`` is NULL (conversion has no run/dataset-version semantics).

The copy preserves insertion order by inserting ``ORDER BY id`` so the new
``event_id`` sequence reproduces the original ``conversion_job_events`` ordering.
After the copy the conversion-private table and its indexes are dropped.

The ``downgrade()`` is the structural inverse: it recreates
``conversion_job_events`` (with its original enum columns, FK, and indexes),
copies the ``stage = 'conversion'`` rows back, and removes them from
``pipeline_events`` so the relocation does not leave duplicates.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "e1f2a3b4c5d6"
down_revision: str | None = "d0e1f2a3b4c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Conversion event-kind values, kept in sync with ``ConversionEventKind`` — used
# only by ``downgrade()`` when recreating the conversion-private enum column.
_CONVERSION_EVENT_KIND_NAMES = (
    "queued",
    "claimed",
    "phase",
    "cancelled",
    "failed",
    "succeeded",
    "upload_pending",
    "recovered_stale",
    "source_enriched",
)

_CONVERSION_JOB_STATUS_NAMES = (
    "NEW",
    "QUEUED",
    "RUNNING",
    "UPLOAD_PENDING",
    "SUCCEEDED",
    "FAILED_RETRYABLE",
    "FAILED_PERM",
    "CANCELLED",
)


def upgrade() -> None:
    """Copy conversion_job_events rows into pipeline_events, then drop the old table."""
    # Content-preserving row copy. ``stage`` is constant, ``work_unit_ref`` is the
    # job id rendered to text (NULL job_id -> 'None' to satisfy NOT NULL while
    # preserving the deleted-job audit row), ``run_id`` is NULL. All other columns
    # carry over verbatim. ``ORDER BY id`` makes the new event_id order reproduce
    # the original insertion order.
    op.execute(
        sa.text(
            "INSERT INTO pipeline_events "
            "(stage, work_unit_ref, run_id, aizk_uuid, from_status, to_status, "
            " kind, attempt, occurred_at, payload_json) "
            "SELECT 'conversion', COALESCE(CAST(job_id AS TEXT), 'None'), NULL, "
            "       aizk_uuid, from_status, to_status, kind, attempt, occurred_at, payload_json "
            "FROM conversion_job_events "
            "ORDER BY id"
        )
    )

    with op.batch_alter_table("conversion_job_events", schema=None) as batch_op:
        batch_op.drop_index("ix_conversion_job_events_kind_occurred_at")
        batch_op.drop_index("ix_conversion_job_events_aizk_uuid_occurred_at")
        batch_op.drop_index("ix_conversion_job_events_job_id_occurred_at")
    op.drop_table("conversion_job_events")


def downgrade() -> None:
    """Recreate conversion_job_events, copy conversion rows back, and remove them from pipeline_events."""
    op.create_table(
        "conversion_job_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "kind",
            sa.Enum(*_CONVERSION_EVENT_KIND_NAMES, name="conversioneventkind"),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            sa.Enum(*_CONVERSION_JOB_STATUS_NAMES, name="conversionjobstatus"),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(*_CONVERSION_JOB_STATUS_NAMES, name="conversionjobstatus"),
            nullable=True,
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["conversion_jobs.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversion_job_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversion_job_events_job_id_occurred_at",
            ["job_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversion_job_events_aizk_uuid_occurred_at",
            ["aizk_uuid", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversion_job_events_kind_occurred_at",
            ["kind", "occurred_at"],
            unique=False,
        )

    # Copy conversion rows back, reversing the work_unit_ref -> job_id mapping
    # ('None' restores to NULL job_id). Preserve order via ORDER BY event_id.
    op.execute(
        sa.text(
            "INSERT INTO conversion_job_events "
            "(job_id, aizk_uuid, attempt, occurred_at, kind, from_status, to_status, payload_json) "
            "SELECT CASE WHEN work_unit_ref = 'None' THEN NULL "
            "            ELSE CAST(work_unit_ref AS INTEGER) END, "
            "       aizk_uuid, attempt, occurred_at, kind, from_status, to_status, payload_json "
            "FROM pipeline_events "
            "WHERE stage = 'conversion' "
            "ORDER BY event_id"
        )
    )
    op.execute(sa.text("DELETE FROM pipeline_events WHERE stage = 'conversion'"))
