"""Add graph-stage chunk persistence and contextualization tables.

Revision ID: f8b9c0d1e2a3
Revises: e1f2a3b4c5d6
Create Date: 2026-05-31 12:00:00.000000

Creates the additive tables owned by ``aizk.graph`` on the stable-identity model
(facts split by what they are about, generation-varying facts off the shared
content-addressed identity):

- ``graph_chunks`` — content-addressed, immutable chunk rows keyed by
  ``chunk_id`` carrying **stable identity facts only** (source ``doc_id`` =
  ``str(aizk_uuid)``, ``text``, ``content_hash``, ``char_count``,
  ``heading_path``, ``ordinal``); run-independent so an unchanged chunk keeps its
  identity across re-chunks.
- ``graph_chunk_run_inputs`` — one row per chunking run recording what it
  consumed: the ``conversion_output_id`` locator and the ``markdown_hash_xx64``
  that verifies it. ``run_id`` is a logical reference to ``pipeline_runs.id`` (no
  foreign key).
- ``graph_chunk_run_manifest`` — append-only ``(run_id, chunk_id, span)``
  recording what a run produced and where each chunk sat in that generation's
  markdown. ``run_id`` is a logical reference to ``pipeline_runs.id`` (no foreign
  key); ``chunk_id`` foreign keys into ``graph_chunks``.
- ``graph_document_summaries`` — run-scoped per-document summary carrying the
  source markdown hash, the consumed ``conversion_output_id`` provenance, and
  ``summary_version``.
- ``graph_contextualized_chunks`` — run-scoped per-chunk contextualized variant
  storing the model's self-contained revision of the chunk (empty when already
  self-contained), carrying the source ``chunk_id``, ``context_version``, the
  ``summary_run_id`` and ``chunking_run_id`` provenance pointers, and the
  derivation key.

These live in the conversion Alembic tree, which owns all tables for the single
SQLite database (ADR-003). The run / dataset-version primitive and the
transition-event log are reused from ``aizk.pipeline`` and are not recreated here.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "f8b9c0d1e2a3"
down_revision: str | None = "e1f2a3b4c5d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the graph-stage chunk, input, manifest, summary, and variant tables."""
    op.create_table(
        "graph_chunks",
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("doc_id", sa.String(), nullable=False),
        sa.Column("heading_path_json", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        "ix_graph_chunks_doc_id",
        "graph_chunks",
        ["doc_id"],
        unique=False,
    )

    op.create_table(
        "graph_chunk_run_inputs",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("conversion_output_id", sa.String(), nullable=False),
        sa.Column("markdown_hash_xx64", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )

    op.create_table(
        "graph_chunk_run_manifest",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.Column("span_start", sa.Integer(), nullable=False),
        sa.Column("span_end", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["graph_chunks.chunk_id"]),
        sa.PrimaryKeyConstraint("run_id", "chunk_id"),
    )
    op.create_index(
        "ix_graph_chunk_run_manifest_chunk_id",
        "graph_chunk_run_manifest",
        ["chunk_id"],
        unique=False,
    )

    op.create_table(
        "graph_document_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("conversion_output_id", sa.String(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("markdown_hash_xx64", sa.String(), nullable=False),
        sa.Column("summary_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_graph_document_summaries_run_id"),
    )
    op.create_index(
        "ix_graph_document_summaries_run_id",
        "graph_document_summaries",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_document_summaries_conversion_output_id",
        "graph_document_summaries",
        ["conversion_output_id"],
        unique=False,
    )

    op.create_table(
        "graph_contextualized_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("summary_run_id", sa.Integer(), nullable=False),
        sa.Column("chunking_run_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.Column("context_version", sa.Integer(), nullable=False),
        sa.Column("contextualized_text", sa.Text(), nullable=False),
        sa.Column("derivation_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["graph_chunks.chunk_id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "chunk_id", name="uq_graph_contextualized_chunks_run_chunk"),
    )
    op.create_index(
        "ix_graph_contextualized_chunks_run_id",
        "graph_contextualized_chunks",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_contextualized_chunks_chunk_id",
        "graph_contextualized_chunks",
        ["chunk_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the graph-stage tables and their indexes."""
    op.drop_index("ix_graph_contextualized_chunks_chunk_id", table_name="graph_contextualized_chunks")
    op.drop_index("ix_graph_contextualized_chunks_run_id", table_name="graph_contextualized_chunks")
    op.drop_table("graph_contextualized_chunks")

    op.drop_index("ix_graph_document_summaries_conversion_output_id", table_name="graph_document_summaries")
    op.drop_index("ix_graph_document_summaries_run_id", table_name="graph_document_summaries")
    op.drop_table("graph_document_summaries")

    op.drop_index("ix_graph_chunk_run_manifest_chunk_id", table_name="graph_chunk_run_manifest")
    op.drop_table("graph_chunk_run_manifest")

    op.drop_table("graph_chunk_run_inputs")

    op.drop_index("ix_graph_chunks_doc_id", table_name="graph_chunks")
    op.drop_table("graph_chunks")
