"""Add graph-stage mention and mention co-occurrence tables.

Revision ID: a2b3c4d5e6f7
Revises: f1a2b3c4d5e6
Create Date: 2026-07-10 12:00:00.000000

Creates the two additive tables owned by ``aizk.graph`` for entity-mention
extraction, reusing the shared ``pipeline_runs`` primitive for the run/
dataset-version scope (no stage-specific run table):

- ``graph_mentions`` — an append-only, run-scoped entity-mention record.
  ``mention_id`` is a surrogate primary key; ``run_id`` is a logical reference to
  ``pipeline_runs.id`` (no foreign key); ``chunk_id`` foreign keys into
  ``graph_chunks``. ``anchor_kind`` (``source`` | ``revision``) and ``input_kind``
  (``raw`` | ``contextualized``) are ``CHECK``-constrained discriminators.
  ``source_span_start`` / ``source_span_end`` / ``source_occurrence_key`` are
  nullable and ``CHECK``-enforced to be populated iff ``anchor_kind = source``.
  Two per-anchor-class partial unique indexes back within-run idempotency (SQL
  ``UNIQUE`` treats ``NULL`` as distinct, so a single index over the nullable span
  would not deduplicate revision-anchored rows).
- ``graph_mention_cooccurrences`` — a flat link table, one row per unordered
  intra-chunk mention pair within a run. Composite primary key
  ``(run_id, mention_id_lo, mention_id_hi)``, a ``CHECK`` enforcing
  ``mention_id_lo < mention_id_hi`` (canonical order, excluding self-pairs), and
  both endpoints foreign-keying into ``graph_mentions.mention_id``.

This lives in the conversion Alembic tree, which owns all tables for the single
SQLite database (ADR-003).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "a2b3c4d5e6f7"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the graph-stage mention and mention co-occurrence tables."""
    op.create_table(
        "graph_mentions",
        sa.Column("mention_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.Column("anchor_kind", sa.String(), nullable=False),
        sa.Column("surface_form", sa.Text(), nullable=False),
        sa.Column("input_kind", sa.String(), nullable=False),
        sa.Column("input_ref", sa.Text(), nullable=False),
        sa.Column("input_span_start", sa.Integer(), nullable=False),
        sa.Column("input_span_end", sa.Integer(), nullable=False),
        sa.Column("source_span_start", sa.Integer(), nullable=True),
        sa.Column("source_span_end", sa.Integer(), nullable=True),
        sa.Column("source_occurrence_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["graph_chunks.chunk_id"]),
        sa.PrimaryKeyConstraint("mention_id"),
        sa.CheckConstraint(
            "anchor_kind IN ('source', 'revision')",
            name="ck_graph_mentions_anchor_kind",
        ),
        sa.CheckConstraint(
            "input_kind IN ('raw', 'contextualized')",
            name="ck_graph_mentions_input_kind",
        ),
        sa.CheckConstraint(
            "anchor_kind != 'source' OR "
            "(source_span_start IS NOT NULL AND source_span_end IS NOT NULL "
            "AND source_occurrence_key IS NOT NULL)",
            name="ck_graph_mentions_source_anchor_fields",
        ),
        sa.CheckConstraint(
            "anchor_kind != 'revision' OR "
            "(source_span_start IS NULL AND source_span_end IS NULL "
            "AND source_occurrence_key IS NULL)",
            name="ck_graph_mentions_revision_anchor_fields",
        ),
    )
    op.create_index(
        "ix_graph_mentions_run_id",
        "graph_mentions",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_mentions_chunk_id",
        "graph_mentions",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        "uq_graph_mentions_source_identity",
        "graph_mentions",
        ["run_id", "chunk_id", "source_span_start", "source_span_end", "surface_form"],
        unique=True,
        sqlite_where=sa.text("anchor_kind = 'source'"),
        postgresql_where=sa.text("anchor_kind = 'source'"),
    )
    op.create_index(
        "uq_graph_mentions_revision_identity",
        "graph_mentions",
        ["run_id", "chunk_id", "surface_form"],
        unique=True,
        sqlite_where=sa.text("anchor_kind = 'revision'"),
        postgresql_where=sa.text("anchor_kind = 'revision'"),
    )

    op.create_table(
        "graph_mention_cooccurrences",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("mention_id_lo", sa.String(), nullable=False),
        sa.Column("mention_id_hi", sa.String(), nullable=False),
        sa.Column("chunk_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["mention_id_lo"], ["graph_mentions.mention_id"]),
        sa.ForeignKeyConstraint(["mention_id_hi"], ["graph_mentions.mention_id"]),
        sa.PrimaryKeyConstraint("run_id", "mention_id_lo", "mention_id_hi"),
        sa.CheckConstraint(
            "mention_id_lo < mention_id_hi",
            name="ck_graph_mention_cooccurrences_ordered",
        ),
    )
    op.create_index(
        "ix_graph_mention_cooccurrences_chunk_id",
        "graph_mention_cooccurrences",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_mention_cooccurrences_hi",
        "graph_mention_cooccurrences",
        ["mention_id_hi"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the graph-stage mention co-occurrence and mention tables."""
    op.drop_index("ix_graph_mention_cooccurrences_hi", table_name="graph_mention_cooccurrences")
    op.drop_index("ix_graph_mention_cooccurrences_chunk_id", table_name="graph_mention_cooccurrences")
    op.drop_table("graph_mention_cooccurrences")

    op.drop_index("uq_graph_mentions_revision_identity", table_name="graph_mentions")
    op.drop_index("uq_graph_mentions_source_identity", table_name="graph_mentions")
    op.drop_index("ix_graph_mentions_chunk_id", table_name="graph_mentions")
    op.drop_index("ix_graph_mentions_run_id", table_name="graph_mentions")
    op.drop_table("graph_mentions")
