"""Add conversion_job_events table for the append-only event log.

Revision ID: a8c9d0e1f2b3
Revises: f7a8b9c0d1e2
Create Date: 2026-05-17 12:00:00.000000

Creates the durable append-only event log for conversion job lifecycle
transitions. The table denormalizes ``aizk_uuid`` from
``conversion_jobs.aizk_uuid`` so audit queries continue working after a
job is deleted via the API delete endpoint — the FK is configured with
``ON DELETE SET NULL`` so event rows survive operator deletions and
remain queryable by Source identity.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "a8c9d0e1f2b3"
down_revision: str | None = "f7a8b9c0d1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_CONVERSION_EVENT_KIND_NAMES = (
    "queued",
    "claimed",
    "phase",
    "cancelled",
    "failed",
    "succeeded",
    "upload_pending",
    "recovered_stale",
    "source_enriched",
)


def upgrade() -> None:
    """Create conversion_job_events with composite indexes and FK ON DELETE SET NULL."""
    op.create_table(
        "conversion_job_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("aizk_uuid", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "kind",
            sa.Enum(*_CONVERSION_EVENT_KIND_NAMES, name="conversioneventkind"),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "QUEUED",
                "RUNNING",
                "UPLOAD_PENDING",
                "SUCCEEDED",
                "FAILED_RETRYABLE",
                "FAILED_PERM",
                "CANCELLED",
                name="conversionjobstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "QUEUED",
                "RUNNING",
                "UPLOAD_PENDING",
                "SUCCEEDED",
                "FAILED_RETRYABLE",
                "FAILED_PERM",
                "CANCELLED",
                name="conversionjobstatus",
            ),
            nullable=True,
        ),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["conversion_jobs.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversion_job_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversion_job_events_job_id_occurred_at",
            ["job_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversion_job_events_aizk_uuid_occurred_at",
            ["aizk_uuid", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversion_job_events_kind_occurred_at",
            ["kind", "occurred_at"],
            unique=False,
        )


def downgrade() -> None:
    """Drop the conversion_job_events table and its indexes."""
    with op.batch_alter_table("conversion_job_events", schema=None) as batch_op:
        batch_op.drop_index("ix_conversion_job_events_kind_occurred_at")
        batch_op.drop_index("ix_conversion_job_events_aizk_uuid_occurred_at")
        batch_op.drop_index("ix_conversion_job_events_job_id_occurred_at")

    op.drop_table("conversion_job_events")
