"""Add the graph extraction work-unit table.

Revision ID: b3c4d5e6f7a8
Revises: a2b3c4d5e6f7
Create Date: 2026-07-12 12:00:00.000000

Creates ``graph_extraction_jobs`` — the extraction stage's claimable work-unit
table, mirroring ``graph_contextualization_jobs``: one row per source to
extract, scoped to the durable source identity ``source_id``. Unlike the
contextualization work-unit, it carries no upstream artifact locator column
(``extract_document`` resolves the source's active chunking run and
contextualized variants directly from ``source_id``); the extractor choice
and input policy are worker configuration, not columns on this table. The
``status`` column mirrors the runtime's ``WorkUnitStatus`` (plain text, no
named enum), and the ``*_at`` columns carry retry/lease scheduling.

Lives in the conversion Alembic tree, which owns all tables for the single
SQLite database (ADR-003).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401 — AutoString referenced in autogenerated DDL

# revision identifiers, used by Alembic.
revision: str = "b3c4d5e6f7a8"
down_revision: str | None = "a2b3c4d5e6f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the graph extraction work-unit table and its indexes."""
    op.create_table(
        "graph_extraction_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("earliest_next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_graph_extraction_jobs_idempotency_key"),
    )
    op.create_index(
        "ix_graph_extraction_jobs_claim",
        "graph_extraction_jobs",
        ["status", "earliest_next_attempt_at", "queued_at"],
        unique=False,
    )
    op.create_index(
        "ix_graph_extraction_jobs_source_id",
        "graph_extraction_jobs",
        ["source_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the graph extraction work-unit table and its indexes."""
    op.drop_index("ix_graph_extraction_jobs_source_id", table_name="graph_extraction_jobs")
    op.drop_index("ix_graph_extraction_jobs_claim", table_name="graph_extraction_jobs")
    op.drop_table("graph_extraction_jobs")
